# Generated by Django 3.1.2 on 2020-10-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blogs.blog'),
        ),
    ]
