# Generated by Django 3.1.2 on 2020-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201015_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blogs.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_readed',
            field=models.ManyToManyField(blank=True, to='blogs.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.ManyToManyField(blank=True, to='blogs.Blog'),
        ),
    ]
