# Generated by Django 3.1.2 on 2020-10-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201015_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_of_creation']},
        ),
    ]
