# Generated by Django 3.1.2 on 2020-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201015_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blogs.Post'),
        ),
    ]
